"""agregar datos de residencia y fecha de registro

Revision ID: 3703c8ad3382
Revises: dbe893a3e2ac
Create Date: 2026-10-01 20:59:00.540983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3703c8ad3382'
down_revision = 'dbe893a3e2ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ciudad_residencia', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('pais_residencia', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('fecha_registro', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('fecha_registro')
        batch_op.drop_column('pais_residencia')
        batch_op.drop_column('ciudad_residencia')

    # ### end Alembic commands ###
