"""empty message

Revision ID: 805306012c7f
Revises: 
Create Date: 2026-09-28 00:37:29.703796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '805306012c7f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habitaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_hab', sa.Integer(), nullable=False),
    sa.Column('tipo_hab', sa.String(), nullable=False),
    sa.Column('precio_noche_hab', sa.Double(), nullable=False),
    sa.Column('estado_hab', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('habitaciones')
    # ### end Alembic commands ###
