"""crear tabla reservas

Revision ID: dcecd60d1d80
Revises: 3703c8ad3382
Create Date: 2026-10-02 05:40:22.919125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcecd60d1d80'
down_revision = '3703c8ad3382'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('habitacion_id', sa.Integer(), nullable=False),
    sa.Column('fecha_entrada', sa.Date(), nullable=False),
    sa.Column('fecha_salida', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['habitacion_id'], ['habitaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservas')
    # ### end Alembic commands ###
